FROM openjdk:17-alpine
MAINTAINER JoostAndTygo
COPY /target/Eindopdracht-1-taskservice-0.0.1-SNAPSHOT.jar Eindopdracht-1-taskservice-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/Eindopdracht-1-taskservice-0.0.1-SNAPSHOT.jar"]

