FROM openjdk:17-alpine
MAINTAINER JoostAndTygo
COPY Eindopdracht-1-taskservice/target/eindopdracht-1-0.0.1-SNAPSHOT.jar eindopdracht-1-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/eindopdracht-1-0.0.1-SNAPSHOT.jar"]

