name: Frontend pipeline

on:
  push:
    branches: [ "master" ]
    paths:
      - 'Eindopdracht-1-user-interface/**'
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: './Eindopdracht-1-user-interface/task-frontend'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js v17.x
        uses: actions/setup-node@v3
        with:
          node-version: '17.x'
      - name: Install dependencies
        run: npm install
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Build production version
        run: ng build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Upload to S3
        run: aws s3 sync dist/Eindopdracht-1-user-interface s3://eindopdracht-bucket/