name: Deployment pipeline

on:
  workflow_dispatch:
    inputs:
      version:
        description: Release to deploy
        type: string
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy container to EC2
        working-directory: Eindopdracht-1-taskservice
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOSTNAME: ${{ secrets.HOST_NAME_FIRST  }}
          USER_NAME : ${{ secrets.USER_NAME  }}
          ECR_REGISTRY: 890231107819.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: eindopdracht-ecr
          IMAGE_TAG: ${{ github.event.inputs.version }}
        run: |
          echo "Image to deploy: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"
          echo "${PRIVATE_KEY}" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} "
            echo \"Image to deploy: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}\"
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${ECR_REGISTRY}/${ECR_REPOSITORY}
            docker rm -f Eindopdracht-1-taskservice
            docker run -d -p 8080:8080 -e SPRING_PROFILES_ACTIVE=prod --name Eindopdracht-1-taskservice ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG} 
          "
