name: Frontend pipeline

on:
  push:
    branches: [ "master" ]
    paths:
      - 'Eindopdracht-1-user-interface/**'
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: "./Eindopdracht-1-user-interface/task-frontend"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js v17.x
        uses: actions/setup-node@v3
        with:
          node-version: '17.x'
      - name: Install dependencies
        run: npm install
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Build production version
        run: ng build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ASIA46RPIWDVV6JTIU7E
          aws-secret-access-key: mTQwvH0eIfjhvhM2lczYTSk0JgtrRsu+cr1NkldR
          aws-session-token: FwoGZXIvYXdzEMT//////////wEaDPa2vZER/O7vUb6EUSK+Abro1u3guQtpMA3UzfHNKy+V1mEhhw0NeiWgZ8ak5NFr3+3FJHBtFk/w+eR40cSaO1fl0hbapFOqCmtKNE33+YcX4BcsxPGgrNVzzd7IwJHWUGr/+0eeFba0A0fqM1T1jNkERvCkpV5XZUjOMdb75cWgv6Q3wQhW26XhPbnva9txH1qsFIKDnUZCUdxuxmBXAoqvTvk2wdC1ORhGhpGx3s9U53iCErlJHHauIvVVoOtdRCi8axV3VY5mnPCsYTIo1YPPmgYyLbluZdwWmNbLCZAT7BTWxj3qjoP0eiRseAoqA50WJIippCgYxj/SOgVeWiCzgw==
          aws-region: us-east-1

      - name: Upload to S3
        run: aws s3 sync dist/eindopdracht-1 s3://eindopdracht-bucket/
