name: Frontend pipeline

on:
  push:
    branches: [ "master" ]
    paths:
      - 'Eindopdracht-1-user-interface/**'
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: "./Eindopdracht-1-user-interface/task-frontend"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js v17.x
        uses: actions/setup-node@v3
        with:
          node-version: '17.x'
      - name: Install dependencies
        run: npm install
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Build production version
        run: ng build
      - name: Code Analysis
        working-directory: Eindopdracht-1-user-interface
        run: |
          mvn sonar:sonar \
          -Dsonar.projectKey=eindopdracht-1-tygo-joost \
          -Dsonar.host.url=http://sonar.cloud-native-minor.it/ \
          -Dsonar.login=45d50dd41d616b6d7bcb94387588d9ea2a89c7da
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Upload to S3
        run: aws s3 sync dist/eindopdracht-1 s3://eindopdracht-bucket/
