name: Java CI

on:
  push:
    branches: [ "master" ]
    paths:
      - 'Eindopdracht-1-taskservice/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        working-directory: Eindopdracht-1-taskservice
        run: mvn -B install --file pom.xml

      - name: Code Analysis
        working-directory: Eindopdracht-1-taskservice
        run: |
          mvn sonar:sonar \
          -Dsonar.projectKey=eindopdracht-1-tygo-joost \
          -Dsonar.host.url=http://sonar.cloud-native-minor.it/ \
          -Dsonar.login=45d50dd41d616b6d7bcb94387588d9ea2a89c7da

      - name: Build the Docker image
        working-directory: Eindopdracht-1-taskservice
        run: docker build . --file Dockerfile --tag eindopdracht-ecr:v$GITHUB_RUN_NUMBER

      - name: Tag the build version
        run: |
          git tag "Build-v$GITHUB_RUN_NUMBER"
          git push origin "Build-v$GITHUB_RUN_NUMBER"
