name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
#      - name: Code Analysis
#          run: |
#            mvn -B sonar:sonar -Dsonar.projectKey=assiignment-1-3-4 \
#            -Dsonar.projectName=awassink-assignment-1-3-4 \
#            -Dsonar.host.url=http://sonar.cloud-native-minor.it \
#            -Dsonar.login=8a11fa433ad37afb91054034111a18421243157c \
#            -Dsonar.qualitygate.wait=true \
#            -Dsonar.qualitygate.timeout=60 \
#            -Dsonar.branch.name=$CI_BRANCH_NAME
#          working-directory: assignment-1-3-4

      - name: Build the Docker image
      run: docker build . --file Dockerfile
      working-directory: Eindopdracht-1